spring:
    application:
        name: registration

    datasource:
        url: jdbc:postgresql://localhost:5432/registration
        username: postgres
        password: qqqq

    jpa:
        hibernate: 
            ddl-auto: update
                        
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
    
    mail:
        host: smtp.gmail.com
        port: 587
        username: joopcheikh48@gmail.com
        password: joopcheikh48600
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
        
server:
    port: 8089




