spring:
    application:
        name: registration

    datasource:
        url: jdbc:postgresql://localhost:5432/registration
        username: postgres
        password: aaaa

    jpa:
        hibernate: 
            ddl-auto: update
                        
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        
server:
    port: 8089




